# Generated by Django 3.1.2 on 2020-10-28 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.items')),
            ],
        ),
        migrations.CreateModel(
            name='allorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=1000)),
                ('item', models.ManyToManyField(to='pro.order_count')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
